"""Add column created_at to project member model

Revision ID: a8456dd4ebe3
Revises: a45057cf56ef
Create Date: 2025-07-15 15:43:28.346391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8456dd4ebe3'
down_revision: Union[str, None] = 'a45057cf56ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_operator_id'), 'audit_log', ['operator_id'], unique=False)
    op.create_index(op.f('ix_conversation_project_id'), 'conversation', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_index(op.f('ix_data_source_project_id'), 'data_source', ['project_id'], unique=False)
    op.create_index(op.f('ix_dataset_project_id'), 'dataset', ['project_id'], unique=False)
    op.add_column('project_member', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('project_member', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_project_member_project_id'), 'project_member', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_member_user_id'), 'project_member', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_member_user_id'), table_name='project_member')
    op.drop_index(op.f('ix_project_member_project_id'), table_name='project_member')
    op.drop_column('project_member', 'updated_at')
    op.drop_column('project_member', 'created_at')
    op.drop_index(op.f('ix_dataset_project_id'), table_name='dataset')
    op.drop_index(op.f('ix_data_source_project_id'), table_name='data_source')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_project_id'), table_name='conversation')
    op.drop_index(op.f('ix_audit_log_operator_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###